spring:
    datasource:
        driverClassName: org.h2.Driver
        password: root
        url: jdbc:h2:mem:SampleDB
        username: root
    h2:
        console:
            enabled: true
    settings:
        web-allow-others: true
    